#!/bin/bash

cfg=$1
env=$2
out=$3

flatname=$(echo "$cfg" | sed 's@/@_@g')
zipname="$flatname.zip"
dirname="$flatname"

set -ex

mkdir -p .zip/$dirname
ln -sf "$(pwd)" ".zip/$flatname/src"
ln -sf "$(pwd)/.pio/build/$env" ".zip/$flatname/bin"
(cd ".zip" && zip -pr "$zipname" "$dirname/src"/* "$dirname/bin/$out")
